# Use Nginx to serve static files
FROM nginx:alpine

# Copy the Vanilla JS frontend files to Nginx's default public directory
COPY . /usr/share/nginx/html

# Expose the port Nginx will run on
EXPOSE 80

# Nginx runs by default
